### ISSUE TITLE
птица не разбивается об пол

### ISSUE THREAD

**Issue by evzhen** [MariaLuna459/Bird-Game#1]
![image](https://user-images.githubusercontent.com/65463560/161096868-1e83f38e-aed3-4c5f-a3ba-13479ef82d09.png)

**Comment by MariaLuna459** [comment]
https://github.com/MariaLuna459/Bird-Game/commit/949786fc20bdab83d5bf24cb150d5bb8b65018ce

**Comment by MariaLuna459** [comment]
https://github.com/MariaLuna459/Bird-Game/commit/949786fc20bdab83d5bf24cb150d5bb8b65018ce
